---
- hosts: middleware
  become: yes
  vars:
    req_java: java-11-openjdk
    set_java: jre-11-openjdk
    req_tomcat_version: 9.0.35
    tomcat_url: http://mirror.nbtelecom.com.br/apache/tomcat/tomcat-{{req_tomcat_version.split(".")[0]}}/v{{req_tomcat_version}}/bin/apache-tomcat-{{req_tomcat_version}}.tar.gz
  tasks:
    - name: Updating all packages on Centos 7
      yum:
        name: "*"
        state: latest 
    - name: Installing required java-11-openjdk
      yum: 
        name: "{{req_java}}"
        state: present
    - name: Setting default Java 11 - OpenJDK
      alternatives:
        name: java
        link: /usr/bin/java
        path: /usr/lib/jvm/{{set_java}}/bin/java 
    - name: Download required tomcat
      get_url:
        url: "{{tomcat_url}}"
        dest: /u01
    - name: Extract apache-tomcat-{{req_tomcat_version}}.tar.gz into /u01
      unarchive:
        src: /u01/apache-tomcat-{{req_tomcat_version}}.tar.gz
        dest: /u01
    - name: Rename directory apache-tomcat-{{req_tomcat_version}} to name jvm1
        src: /u01/apache-tomcat-{{req_tomcat_version}}
        dest: /u01/jvm1

